### ISSUE TITLE
Fresh docker install of   ghcr.io/tasmoadmin/tasmoadmin:latest results in "File not found" and nginx "Primary script unknown"

### ISSUE THREAD

**Issue by simowilso** [TasmoAdmin/TasmoAdmin#1067]
## Expected Behavior
Tasmoadmin login/web page should appear

## Current Behavior
"File not found" is displayed

## Steps to Reproduce

1. install latest (as of 1st January 2024) docker container and run it
2.
3.
4.

## Context (Environment)
Raspberry pi5, docker.

## Possible Implementation

I tried copying nginx-ssl.conf to nginx.conf inside the container, but the problem remains.

**Comment by inverse** [comment]
What command are you using to run?

```
docker run -it -p 8000:80 ghcr.io/tasmoadmin/tasmoadmin:latest
```

running this works ofr me when display navigating to localhost:8000

**Comment by simowilso** [comment]
Hmmm. It works for me too. I'm trying to get all my containers into docker compose. I used:

Is there a simpler one?


  tasmoadmin:
    container_name: tasmoadmin
    image: ghcr.io/tasmoadmin/tasmoadmin
    volumes:
      - /home/ubuntu/tasmoadmin/:/var/www/tasmoadmin
      - /home/ubuntu/tasmoadmin/:/data/tasmoadmin

    ports:
      - 5555:80
    environment:
      - TASMO_DATADIR=/data/tasmoadmin/
      - TASMO_DEBUG=1

**Comment by inverse** [comment]
Sounds like it's the first volume you're mounting perhaps?  That one we have in the project root is for mounting the source code to the container for dev flow (`/home/ubuntu/tasmoadmin/:/var/www/tasmoadmin)`.

Perhaps something like this would work for you.

```yaml
version: "3.9"
services:
  tasmoadmin:
    container_name: tasmoadmin
    image: ghcr.io/tasmoadmin/tasmoadmin:latest
    volumes:
      - /home/ubuntu/tasmoadmin/data:/data/tasmoadmin
    ports:
      - 5555:80
    environment:
      - TASMO_DATADIR=/data/tasmoadmin/
```

Not sure you'll need the `TASMO_DEBUG` env var as that's for debug purposes
