### ISSUE TITLE
When starting auto-update I have an error: "Failed to fetch"

### ISSUE THREAD

**Issue by alexdelprete** [TasmoAdmin/TasmoAdmin#631]
## Expected Behavior
Auto-update should complete

## Current Behavior
I tried to auto-update fw to latest 12.1.0 and I have a weird error:

```
Unable to access OTA URL @ http://tasmoadmin.axel.dom:80/data/firmwares/tasmota.bin.gz - TypeError: Failed to fetch
```

The firmware has been autodownloaded correctly, I can see it in the `data/tasmoadmin/firmwares` folder and a wget of that url from shell works fine.

I see no errors in the log...

## Steps to Reproduce

1. Start auto update, it downloads the fw files correctly to the appropriate folder
2. Select the device, and click Start Update and the error comes up:
![image](https://user-images.githubusercontent.com/7027842/185726558-9a9907b2-0680-4ccc-9141-bc1a078a39a4.png)

## Context (Environment)

- TasmoAdmin v2.1.0-beta9
- Docker

**Comment by inverse** [comment]
Thanks for reporting - looks like a bug with the FE check logic that I remember you saying you had disabled.

**Comment by alexdelprete** [comment]
> looks like a bug with the FE check logic that I remember you saying you had disabled.

I tried with the check disabled and enabled, no difference.

> Perhaps I should remove this feature? the intent was to check that the client side JavaScript can access the firmware...

Well, it's good to have a status check, maybe to be triggered manually with a specific button/link.

> I assume you can download it just fine in your browser using that URL?

Yes, like I wrote in the OP, tried with wget and it worked fine.

> I did have issues with CORS policies which I had to modify the nginx rules in the docker container for that path.

Interesting, I'm using Traefik, this is my default headers config: what did you need to change?
Another question: in previous version everything was working fine, so I guess new code introduced the issue, was it the FE/BE check?

```yaml
    default-headers:
      headers:
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "PATCH"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "*"
        accessControlAllowOriginList:
          - "*"
        accessControlMaxAge: 180
        addVaryHeader: true
        browserXssFilter: true
        # CSP: don't use base-uri 'self' nor form-action 'self'; or frame-ancestors 'self'; they are disruptive for many services script-src 'self'; style-src 'self'; img-src 'self';
        contentSecurityPolicy: object-src 'self';
        contentTypeNosniff: true
        permissionsPolicy: vibrate=(self); geolocation=(self); midi=(self); notifications=(self); push=(self); vibrate=(self); fullscreen=(self); microphone=(); camera=(); magnetometer=(); gyroscope=(); speaker=();
        forceSTSHeader: true
        customFrameOptionsValue: SAMEORIGIN
        hostsProxyHeaders: 
          - "X-Forwarded-Host"
        referrerPolicy: same-origin
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
```
